events {
    worker_connections 1024;
}

http {
    upstream frontend {
    server 65.2.81.44:3000; 
}

    upstream backend {
        server 65.2.81.44:5001;
    }

    server {
        listen 80;
        server_name 65.2.81.44;

        location / {
            root /EXPENSE-V3/frontend/build; 
            proxy_pass http://65.2.81.44:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /api {
            rewrite ^/api(/.*)$ $1 break;
            proxy_pass http://65.2.81.44:5001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}